server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3321/sportscenter_db
    username: root
    password: root
  application:
    name: SportsCenter
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6385
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: complaints.sportscenter@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 2f1d88b1c0b9dcb71c5f2d5be89801906fa2e4d84a3b19b47d3de4e154deeb71
  expiration: 86400000

stripe:
  api:
    key: ${STRIPE_SECRET_KEY}

recommendation:
  service:
    url: http://localhost:8000/recommendations